import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@/styles/fonts.scss";

export const metadata: Metadata = {
  title: "Home Furniture And Decor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
